spring:
  profiles:
    active: "local"
    group:
      "local": "mariadb,common"
      "test": "h2db,common"

---
spring:
  config:
    activate:
      on-profile: "common"
  data:
    rest:
      basePath: "/api"

server:
  port: 3000

---
spring:
  config:
    activate:
      on-profile: "h2db"

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

---
spring:
  config:
    activate:
      on-profile: "mariadb"

  datasource:
    url: jdbc:mariadb://localhost:9700/cardb?useSSL=false
    username: app
    password: app9700
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      format-sql: true